---
title: "Coffee"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message=FALSE, warning=FALSE)
```


```{r}
library(tidyverse)
library(RColorBrewer)

arabica_data_cleaned <- read_csv("data/arabica_data_cleaned.csv") %>%
  # keep only the numbers in the Harvest.Year column
  # need to check for leftover NA rows
  mutate(Harvest.Year = parse_number(Harvest.Year))

robusta_data_cleaned <- read_csv("data/robusta_data_cleaned.csv")

# bind the rows
coffees <- bind_rows(arabica_data_cleaned, robusta_data_cleaned)
```

```{r}
coffees %>% filter(Sweetness>5) %>% 
ggplot( ) + 
   geom_smooth(mapping = aes(x = Total.Cup.Points, y = Sweetness, colour = Species),method="lm") +
  geom_point(mapping = aes(x = Total.Cup.Points, y = Sweetness, colour = Species), 
             alpha = 0.5, 
             position = position_jitter(width = 0, height = 0.01))
```

Shows the correlations between sweetness and cup points where Sweetness is more than 5 and species is Arabica. 

 ```{r}
 #bad graph
# coffees %>% filter(Sweetness>5) %>% 
# ggplot( ) + 
#   geom_point(mapping = aes(x = altitude_mean_meters, y = Sweetness))
 ```

```{r} 
qm<-coffees %>% select(Aroma:Sweetness,Name, Species, Processing.Method,  Rating = Total.Cup.Points) %>% 
  pivot_longer(cols=Aroma:Sweetness,names_to ="qlty",values_to="Score") %>% filter(Score>0)

qm %>% ggplot()+  geom_point(mapping = aes(x = Score, y = Rating, colour = Species ), alpha = 0.5) +
  facet_wrap(~qlty) +
  scale_color_brewer(palette = "Set3")
```


Shows the correlations between different measures and cup points where species is Arabica. 

```{r}
ggplot(data=coffees %>% filter(Total.Cup.Points>5)) + geom_histogram(aes(x=Total.Cup.Points, fill = Species))

```

```{r}
ggplot(data=coffees %>% filter(Total.Cup.Points>5, !(is.na(Country.of.Origin)))) + geom_bar(aes(x= fct_rev(fct_infreq(Country.of.Origin ))))+coord_flip()+ xlab("Country") + 
           ylab("Count")

```


```{r}
ggplot(data=coffees %>% filter(Total.Cup.Points>5, !(is.na(Country.of.Origin)))) +
  geom_bar(aes(x= fct_rev(fct_infreq(Country.of.Origin)),
              fill = Species
               )
           )+
  coord_flip() + xlab("Country") + 
  ylab("Count")

```

TEST
